server:
  host: 127.0.0.1
  port: 8080
  timeout:
    server: 30s
    read: 15s
    write: 10s
    idle: 5s
  maxRequestBodySize: 64KB
redis:
  addr: localhost:6379
  db: 0
  ping:
    enable: true
log:
  level: debug
  format: pretty
  request:
    level: debug