openapi: 3.0.3
info:
  title: Octi Sync Server
  description: |-
    This is the Octi Sync Server.
  contact:
    email: contact@jakob-moeller.de
  license:
    name: Apache 2.0
    url: https://github.com/jakob-moeller-cloud/octi-sync-server/blob/main/LICENSE
  version: v1
externalDocs:
  description: GitHub
  url: https://github.com/jakob-moeller-cloud/octi-sync-server
servers:
  - url: https://grylls.octi.darken.eu/v1
    description: The official Server!
  - url: http://localhost:8080/v1
    description: Run it Locally to try it out!
tags:
  - name: auth
    description: Everything Related to Authentication
  - name: modules
    description: Access to Sync Modules
  - name: devices
    description: Interact with registered devices to your account
  - name: health
    description: Access to Healthiness / Readiness Information
paths:
  /ready:
    get:
      tags:
        - health
      operationId: isReady
      summary: Checks if the Service is Operational
      description: Performs a Readiness check (with dependencies included)
      responses:
        '200':
          description: Successful Readiness
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HealthAggregation'
        '503':
          description: Failure during Readiness Check
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HealthAggregation'
  /health:
    get:
      tags:
        - health
      operationId: isHealthy
      summary: Checks if the Service is Available for Processing Request
      description: Performs a Health check of the HTTP Router
      responses:
        '200':
          description: Successful Healthiness
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HealthAggregation'
  /auth/register:
    post:
      tags:
        - auth
      summary: Register A Device
      description: Register a new Device / Account
      operationId: register
      parameters:
        - $ref: '#/components/parameters/XDeviceID'
        - $ref: '#/components/parameters/ShareCode'
      responses:
        '200':
          description: Successful Registration
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RegistrationResult'
  /auth/share:
    post:
      tags:
        - auth
      summary: Share your Account
      description: Creates temporary Share Codes for sharing your Account
      operationId: share
      parameters:
        - $ref: '#/components/parameters/XDeviceID'
      responses:
        '200':
          description: Share Code Response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ShareResponse'
      security:
        - deviceAuth: []
  /devices:
    get:
      tags:
        - devices
      summary: Get All registered Devices for your Account
      description: Receive Device Data for all devices in your Account
      operationId: getDevices
      parameters:
        - $ref: '#/components/parameters/XDeviceID'
      responses:
        '200':
          $ref: '#/components/responses/DeviceListResponse'
      security:
        - deviceAuth: []
  /modules/{name}:
    get:
      tags:
        - modules
      summary: Get Module Data
      description: Receive Streamed Module Data
      operationId: getModule
      parameters:
        - $ref: '#/components/parameters/XDeviceID'
        - $ref: '#/components/parameters/DeviceIDQuery'
        - $ref: '#/components/parameters/ModuleName'
      responses:
        '200':
          $ref: '#/components/responses/ModuleDataResponse'
      security:
        - deviceAuth: []
    post:
      tags:
        - modules
      summary: Create/Update Module Data
      description: Receive Streamed Module Data
      operationId: createModule
      parameters:
        - $ref: '#/components/parameters/XDeviceID'
        - $ref: '#/components/parameters/ModuleName'
      requestBody:
        $ref: '#/components/requestBodies/ModuleDataRequest'
      responses:
        '202':
          $ref: '#/components/responses/ModuleDataAccepted'
      security:
        - deviceAuth: []
components:
  parameters:
    ModuleName:
      name: name
      required: true
      description: "Strict Identifier for a Module"
      in: path
      allowEmptyValue: false
      schema:
        $ref: '#/components/schemas/ModuleName'
    XDeviceID:
      name: X-Device-ID
      in: header
      required: true
      description: |-
        Unique Identifier of the calling Device. If calling Data endpoints, must be presented in order
        to be properly authenticated.
      schema:
        $ref: '#/components/schemas/DeviceID'
    DeviceIDQuery:
      name: device-id
      in: query
      required: false
      description: |-
        Device Identifier to use for the Query. If given, takes precedence over X-Device-ID or other hints.
        Use to query data from devices in your account from another account.
      schema:
        $ref: '#/components/schemas/DeviceID'
    ShareCode:
      name: share
      in: query
      required: false
      description: |-
        The Share Code from the Share API. If presented in combination with a new Device ID, 
        it can be used to add new devices to an account.
      schema:
        type: string
  requestBodies:
    ModuleDataRequest:
      description: Module Data Stream
      content:
        application/octet-stream:
          schema:
            $ref: '#/components/schemas/ModuleDataStream'
  responses:
    DeviceListResponse:
      description: Device List containing multiple Devices
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/DeviceList'
    ModuleDataAccepted:
      description: Module Data got Accepted for Processing
      content:
        application/json:
          schema:
            description: "An Empty JSON"
    ModuleDataResponse:
      description: Module Data Stream
      content:
        application/octet-stream:
          schema:
            $ref: '#/components/schemas/ModuleDataStream'
  schemas:
    DeviceID:
      type: string
      description: "Device ID is the unique identifier for a remote device"
      format: uuid
    HealthAggregationComponent:
      type: object
      properties:
        name:
          type: string
          description: "The Name of the Component to be Health Checked"
        health:
          $ref: '#/components/schemas/HealthResult'
      required:
        - name
        - health
    HealthResult:
      type: string
      description: "A Health Check Result"
      enum:
        - "Up"
        - "Down"
    HealthAggregation:
      type: object
      properties:
        health:
          $ref: '#/components/schemas/HealthResult'
        components:
          description: "The different Components of the Server"
          type: array
          items:
            $ref: '#/components/schemas/HealthAggregationComponent'
      required:
        - health
    ListItemCount:
      type: integer
      description: "Amount of Items contained in List"
    Device:
      type: object
      description: "a device"
      properties:
        id:
          $ref: '#/components/schemas/DeviceID'
      required:
        - id
    DeviceList:
      type: object
      description: "list of devices"
      properties:
        count:
          $ref: "#/components/schemas/ListItemCount"
        items:
          description: "array of devices, it will always at least contain the device of the authenticated user"
          type: array
          minItems: 1
          uniqueItems: true
          items:
            $ref: '#/components/schemas/Device'
      required:
        - count
        - items
    ModuleDataStream:
      type: string
      format: binary
      description: "Module Data Stream"
    ModuleName:
      type: string
      description: "Module Name"
    ShareResponse:
      type: object
      properties:
        shareCode:
          type: string
    RegistrationResult:
      type: object
      properties:
        username:
          type: string
        password:
          type: string
      required:
        - username
        - password
  securitySchemes:
    deviceAuth:
      type: http
      scheme: basic
